[package]
name = "mapi"
version = "0.1.0"
authors = ["Noah Altunian <noah@cirruslabs.io"]

[profile.release]
debug = true

[lib]
name = "mapi"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.0"
sysinfo = "0.8.0"
walkdir = "2.2.7"